//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pawel.Workshop.Database.Database_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        public int ID { get; set; }
        public Nullable<int> CID { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public string Poj { get; set; }
        public string Typ { get; set; }
        public string Rok { get; set; }
        public string Rej { get; set; }
        public string Vin { get; set; }
        public string Opis { get; set; }
        public string Silnik { get; set; }
        public Nullable<System.DateTime> Badanie { get; set; }
        public Nullable<int> Licznik { get; set; }
        public Nullable<int> Paliwo { get; set; }
        public Nullable<System.DateTime> DataP { get; set; }
        public Nullable<System.DateTime> DataW { get; set; }
        public Nullable<int> Dowod { get; set; }
    }
}
