//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seller.Database.Database_model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cars> Cars { get; set; }
        public DbSet<Categories> Categories { get; set; }
        public DbSet<Customers> Customers { get; set; }
        public DbSet<ItemsPzWz> ItemsPzWz { get; set; }
        public DbSet<Magazyn> Magazyn { get; set; }
        public DbSet<MagType> MagType { get; set; }
        public DbSet<Programs> Programs { get; set; }
        public DbSet<PZWZ> PZWZ { get; set; }
        public DbSet<Transakcje> Transakcje { get; set; }
        public DbSet<TransItems> TransItems { get; set; }
        public DbSet<Urs> Urs { get; set; }
        public DbSet<Uslugi> Uslugi { get; set; }
        public DbSet<Usterki> Usterki { get; set; }
        public DbSet<Workers> Workers { get; set; }
    }
}
