//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pawel.Workshop.Database.Database_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MagType
    {
        public int ID { get; set; }
        public string MAGAZYN { get; set; }
        public string ADRES { get; set; }
    }
}
