//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pawel.Workshop.Database.Database_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prices
    {
        public Prices()
        {
            this.Programs = new HashSet<Programs>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> BruttoPriceBuy { get; set; }
        public Nullable<decimal> BruttoPriceSell { get; set; }
        public Nullable<bool> IsArchive { get; set; }
    
        public virtual ICollection<Programs> Programs { get; set; }
    }
}
