//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pawel.Workshop.Database.Database_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programs
    {
        public int ID { get; set; }
        public Nullable<int> CATID { get; set; }
        public Nullable<int> CID { get; set; }
        public string NUMERKAT { get; set; }
        public string MODEL { get; set; }
        public string NUMERSER { get; set; }
        public string OPIS { get; set; }
        public string NAZWA { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<decimal> VATPRICE { get; set; }
        public string JEDNOSTKA { get; set; }
        public Nullable<decimal> PROWIZJA { get; set; }
        public Nullable<decimal> PRICE2 { get; set; }
        public Nullable<decimal> VATPRICE2 { get; set; }
        public Nullable<int> Vat { get; set; }
    }
}
