//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pawel.Workshop.Database.Database_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PZWZ
    {
        public int ID { get; set; }
        public Nullable<int> UID { get; set; }
        public Nullable<int> CID { get; set; }
        public Nullable<int> MID { get; set; }
        public Nullable<int> TYPE { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public Nullable<decimal> SUMA { get; set; }
    }
}
