//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pawel.Workshop.Database.Database_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transakcje
    {
        public int ID { get; set; }
        public string NUMER { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<decimal> VATPRICE { get; set; }
        public Nullable<int> CID { get; set; }
        public Nullable<int> UID { get; set; }
        public Nullable<int> PLATNOSC { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string UWAGI { get; set; }
        public Nullable<int> CARID { get; set; }
        public Nullable<System.DateTime> TERMIN { get; set; }
        public Nullable<System.DateTime> TERMINU { get; set; }
        public Nullable<int> Licznik { get; set; }
        public Nullable<int> Paliwo { get; set; }
        public Nullable<int> Dowod { get; set; }
    }
}
