//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pawel.Workshop.Database.Database_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urs
    {
        public int ID { get; set; }
        public string USR { get; set; }
        public string PASS { get; set; }
        public string IMIE { get; set; }
        public string NAZWISKO { get; set; }
        public Nullable<int> PRIV { get; set; }
    }
}
