//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seller.Database.Database_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usterki
    {
        public int ID { get; set; }
        public Nullable<int> CARID { get; set; }
        public string USTERKA { get; set; }
    }
}
